### ISSUE TITLE
repr_png for recordedplot doesn't do anything on Windows

### ISSUE THREAD

**Issue by takluyver** [IRkernel/repr#11]
`capabilities('png')` is TRUE, but the code only checks for aqua/cairo/X11 capabilities. @flying-sheep , is this an oversight, or is there some reason that the png capability alone is not enough?

Ping @asmeurer

**Comment by asmeurer** [comment]
This is the full list of capabilities that I have on Windows:

```

Out[2]:
jpeg
TRUE
png
TRUE
tiff
TRUE
tcltk
TRUE
X11
FALSE
aqua
FALSE
http/ftp
TRUE
sockets
TRUE
libxml
TRUE
fifo
TRUE
cledit
FALSE
iconv
TRUE
NLS
TRUE
profmem
TRUE
cairo
FALSE
ICU
FALSE
long.double
TRUE
```

The notebook generated has a pdf (which isn't great because it's not inline), but that's it.

**Comment by takluyver** [comment]
Adding png to the list of capabilities we check appeared to fix the problem. Hopefully that doesn't have any odd side effects. Presumably we need to do the equivalent for repr_jpg.

**Comment by flying-sheep** [comment]
we discussed that in length in IRkernel/repr#8.

i didn’t check for `capabilities('png')` because if it’s missing, that doesn’t necessarily mean the `png` device won’t work.

adding it to `any(capabilities(c('aqua', 'cairo', 'X11')))` → `any(capabilities(c('aqua', 'cairo', 'X11','png')))` shouldn’t do any harm and could make it work for another class of systems.

damn, this stuff is underdocumented and strange. it’s basically down to guessing intentions and how the stuff could possibly have grown over time to work like it does, and all that without having many differen configurations to test :cry:

**Comment by takluyver** [comment]
Ah, sorry, I'd forgotten that discussion.

The important thing is that png should work when it *is* set, right? It may work if it isn't set, but as part of an `any()` check, that doesn't matter.

I'll make a PR to add it there.

**Comment by flying-sheep** [comment]
> The important thing is that png should work when it *is* set, right? It may work if it isn't set, but as part of an `any()` check, that doesn't matter.

yes, i guess i just forgot to add that.

> I'll make a PR to add it there.

probably no need, i can’t think of a way this could cause problems: if `isTRUE(capabilities('png'))`, how should `png('foobar.png')` fail?

**Comment by asmeurer** [comment]
Cool. Can you ping me whenever you do a release with this change?

**Comment by takluyver** [comment]
Just tagged 0.3

**Comment by asmeurer** [comment]
Awesome. Now plotting works everywhere.
