### ISSUE TITLE
Build repr_*.data.table (and tibble/dplyr equivalent)

### ISSUE THREAD

**Issue by jankatins** [IRkernel/repr#58]
Currently we treat these two data formats the same way as a data.frame by using `as.data.frame()` on them. This can lead to problems if these two are used with bigger datasets.

See https://github.com/IRkernel/IRkernel/issues/127#issuecomment-220438183

**Comment by karldw** [comment]
At some point we want to shrink the data down to a size that's convenient to print and read.  Could we just do all our subsetting, then use `as.data.frame`?  It would still make a copy, but that inefficiency doesn't matter when the table is going to be 60-by-20 at most.

**Comment by janschulz** [comment]
This could run into problems on data.table because as far was I understad it it will reset the "should I print it" flag when you do something with the dt, so subsetting it will then not print the next one...

**Comment by flying-sheep** [comment]
we only do this for [repr_text](https://github.com/IRkernel/repr/blob/68c9b6fa9f1aad8d002b2b4d8f3d9704533576fc/R/repr_matrix_df.r#L222-L225).

@karldw why did you suppress the special printing again in 49a7f58e871e74a0b25ee59eb2e37d4498edb19b? just because of the looks, or because `print.data.table`/`print.tbl` does weird things?

**Comment by karldw** [comment]
Just for the looks, I thought it would be nice to have uniform tablular output for data.frame, data.table and tbl.  Plus it makes testing easier.

**Comment by flying-sheep** [comment]
I like the way it is now, uniform everything, everything configurable, …
